resources:

  lambda:
    target_resource_type: lambda:function
    alarm:
      metrics:
      - Errors
      - Throttled

  apigateway:
    target_resource_type: apigateway:restapi
    alarm:
      metrics:
      - 5XXError

  eventbridge:
    target_resource_type: events:rule
    alarm:
      metrics:
      - FailedInvocations
      - ThrottledRules

  scheduler:
    target_resource_type: scheduler:schedule-group
    alarm:
      metrics:
      - TargetErrorCount
      - TargetErrorThrottledCount
      - InvocationThrottleCount
      - InvocationDroppedCount

  sns:
    target_resource_type: sns:topic
    alarm:
      metrics:
      - NumberOfNotificationsFailed

  sqs-main-queue:
    target_resource_type: sqs:queue
    target_resource_tags:
      alarm-craft:sqs:main-queue: 'true'
    alarm:
      metrics:
      - ApproximateAgeOfOldestMessage
      - ApproximateNumberOfMessagesVisible
      alarm_param_overrides:
        ApproximateAgeOfOldestMessage:
          ComparisonOperator: GreaterThanOrEqualToThreshold
          Threshold: 3600
        ApproximateNumberOfMessagesVisible:
          ComparisonOperator: GreaterThanOrEqualToThreshold
          Threshold: 500

  sqs-dead-letter-queue:
    target_resource_type: sqs:queue
    target_resource_tags:
      alarm-craft:sqs:dlq: 'true'
    alarm:
      metrics:
      - ApproximateNumberOfMessagesVisible
      - ApproximateAgeOfOldestMessage
      alarm_param_overrides:
        ApproximateAgeOfOldestMessage:
          ComparisonOperator: GreaterThanOrEqualToThreshold
          Threshold: 864000

  stepfunctions:
    target_resource_type: states:stateMachine
    alarm:
      metrics:
      - ExecutionsFailed
      - ExecutionsTimedOut
      - ExecutionsAborted
      - ExecutionThrottled