version = 0.1
[default.deploy.parameters]
stack_name = "alarm-craft-autorun"
resolve_s3 = true
s3_prefix = "alarm-craft-autorun"
region = "ap-northeast-1"
profile = "stg2023-admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CodeBuildName=\"codebuild-alarm-craft\" EventName=\"event-cfnstack-trigger-alarm-craft\" SNSTopicName=\"sns-topic-alarm-notification\" LogGroupRetentionInDays=\"5\" AlarmConfigRepositoryCloneUrl=\"https://github.com/ryo-murai/alarm-craft-autorun-codebuild.git\" BranchNameAlarmConfig=\"main\" EventSourceCfnStackNamePrefix=\"health\""
image_repositories = []
