version = 0.1
[default.deploy.parameters]
stack_name = "alarm-craft-autorun"
resolve_s3 = true
s3_prefix = "alarm-craft-autorun"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CodeBuildName=\"codebuild-alarm-craft\" EventName=\"event-cfnstack-trigger-alarm-craft\" AlarmNotifSNSTopicArn=\"\" LogGroupRetentionInDays=\"5\" AlarmConfigRepositoryCloneUrl=\"https://github.com/ryo-murai/alarm-craft-autorun-codebuild.git\" BranchNameAlarmConfig=\"main\" AlarmCraftAdditionalOptions=\"\""
image_repositories = []
