AWSTemplateFormatVersion: "2010-09-09"
Description: >
  alarm-craft automated execution stack

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  CodeBuildName:
    Type: String
    Default: "codebuild-alarm-craft"

  EventName:
    Type: String
    Default: "event-codepipeline-trigger-alarm-craft"

  AlarmNotifSNSTopicArn:
    Type: String
    Default: ""

  LogGroupRetentionInDays:
    Type: Number
    Default: "60"

  AlarmConfigRepositoryType:
    Type: String
    AllowedValues:
      - GITHUB
      - BITBUCKET
      - CODECOMMIT
      - CODEPIPELINE
      - GITHUB
      - GITHUB_ENTERPRISE
      - NO_SOURCE
      - S3
    Default: GITHUB

  AlarmConfigRepositoryCloneUrl:
    Type: String

  BranchNameAlarmConfig:
    Type: String

  AlarmCraftAdditionalOptions:
    Type: String
    Default: ""

  EventSourceCfnStackNamePrefix:
    Type: String
    Default: ""    

  EventStatus:
    Type: String
    AllowedValues:
      - DISABLED
      - ENABLED
    Default: DISABLED

Conditions:
  CreateSNSTopic: !Equals
    - !Ref AlarmNotifSNSTopicArn
    - ""

Resources:

  # ------------------------------------------------------------#
  #  CodeBuild
  # ------------------------------------------------------------#
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildName
      ServiceRole: !GetAtt AlarmCraftCodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: ARM_LAMBDA_CONTAINER
        ComputeType: BUILD_LAMBDA_1GB
        Image: aws/codebuild/amazonlinux-aarch64-lambda-standard:python3.12
        EnvironmentVariables:
          - Name: topic
            Type: PLAINTEXT
            Value: !If
              - CreateSNSTopic
              - !GetAtt SNSTopic.TopicArn
              - !Ref AlarmNotifSNSTopicArn
          - Name: alarmcraft_opts
            Type: PLAINTEXT
            Value: !Ref AlarmCraftAdditionalOptions
      Source:
        Type: !Ref AlarmConfigRepositoryType
        Location: !Ref AlarmConfigRepositoryCloneUrl
        GitCloneDepth: 1
      SourceVersion: !Ref BranchNameAlarmConfig
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  # ------------------------------------------------------------#
  #  Log Group
  # ------------------------------------------------------------#
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub "/aws/codebuild/${BuildProject}"
      RetentionInDays: !Ref LogGroupRetentionInDays

  # ------------------------------------------------------------#
  #  EventBridge
  # ------------------------------------------------------------#
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref EventName
      EventPattern:
        source:
          - aws.cloudformation
        detail-type:
          - CloudFormation Stack Status Change
        detail:
          stack-id:
            - prefix: !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${EventSourceCfnStackNamePrefix}"
          status-details:
            status:
              - CREATE_COMPLETE
              - UPDATE_COMPLETE
              - DELETE_COMPLETE
      State: !Ref EventStatus
      Targets:
        - Id: run-alarm-craft
          Arn: !Sub "arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:project/${BuildProject}"          
          RoleArn: !GetAtt EventBridgeRole.Arn

  # ------------------------------------------------------------#
  #  SNS
  # ------------------------------------------------------------#
  SNSTopic:
    Condition: CreateSNSTopic
    Type: AWS::SNS::Topic

  # ------------------------------------------------------------#
  #  IAM
  # ------------------------------------------------------------#
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
      Path: /
      Policies:
        - PolicyName: EventBridgeAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuild
                Effect: Allow
                Action:
                  - codebuild:*
                Resource: "*"

  AlarmCraftCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Sid: AlarmCraftAccess
                Effect: Allow
                Action:
                  - resourcegroupstaggingapi:GetResources
                  - apigateway:Get
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                  - tag:GetResources
                Resource: "*"

Outputs:
  SNSTopic:
    Condition: CreateSNSTopic
    Value: !Ref SNSTopic